DROP TABLE IF EXISTS Avaliacao CASCADE;
DROP TABLE IF EXISTS Episodio CASCADE;
DROP TABLE IF EXISTS Temporada CASCADE;
DROP TABLE IF EXISTS Serie_Genero CASCADE;
DROP TABLE IF EXISTS Serie_Status CASCADE;
DROP TABLE IF EXISTS Serie CASCADE;
DROP TABLE IF EXISTS Genero_Usuario CASCADE;
DROP TABLE IF EXISTS Usuario CASCADE;
DROP TABLE IF EXISTS Pais CASCADE;

