INSERT INTO Serie_Status (serie_nome, status) VALUES
('Black Mirror', 'finalizada'),
('Breaking Bad', 'finalizada'),
('Chernobyl', 'finalizada'),
('Dark', 'finalizada'),
('Dexter', 'finalizada'),
('Fleabag', 'finalizada'),
('Friends', 'finalizada'),
('Game of Thrones', 'finalizada'),
('How I Met Your Mother', 'finalizada'),
('Lucifer', 'finalizada'),
('Modern Family', 'finalizada'),
('Narcos', 'finalizada'),
('Peaky Blinders', 'finalizada'),
('Rick and Morty', 'em andamento'),
('Sherlock', 'finalizada'),
('Stranger Things', 'em andamento'),
('The 100', 'finalizada'),
('The Big Bang Theory', 'finalizada'),
('The Boys', 'em andamento'),
('The Crown', 'finalizada'),
('The Mandalorian', 'em andamento'),
('The Office', 'finalizada'),
('The Umbrella Academy', 'finalizada'),
('The Walking Dead', 'finalizada'),
('The Witcher', 'em andamento');
