insert into Usuario (email, senha, nome, data_nascimento) VALUES
('ana.silva@example.com', 'senhaAna1', 'Ana Silva', '1985-04-12'),
('bruno.costa@example.com', 'senhaBruno2', 'Bruno Costa', '1978-09-23'),
('carla.oliveira@example.com', 'senhaCarla3', 'Carla Oliveira', '1990-03-05'),
('daniel.pereira@example.com', 'senhaDaniel4', 'Daniel Pereira', '1982-07-15'),
('eduarda.gomes@example.com', 'senhaEduarda5', 'Eduarda Gomes', '1995-11-30'),
('felipe.santos@example.com', 'senhaFelipe6', 'Felipe Santos', '1988-06-20'),
('gabriela.rocha@example.com', 'senhaGabriela7', 'Gabriela Rocha', '1992-01-18'),
('henrique.souza@example.com', 'senhaHenrique8', 'Henrique Souza', '1980-12-10'),
('isabela.mendes@example.com', 'senhaIsabela9', 'Isabela Mendes', '1997-05-25'),
('joao.martins@example.com', 'senhaJoao10', 'João Martins', '1984-08-08'),
('karina.almeida@example.com', 'senhaKarina11', 'Karina Almeida', '1993-02-14'),
('leonardo.ribeiro@example.com', 'senhaLeonardo12', 'Leonardo Ribeiro', '1987-10-30'),
('mariana.carvalho@example.com', 'senhaMariana13', 'Mariana Carvalho', '1991-04-07'),
('natan.dias@example.com', 'senhaNatan14', 'Natan Dias', '1996-03-21'),
('olivia.azevedo@example.com', 'senhaOlivia15', 'Olivia Azevedo', '1994-09-09'),
('paulo.nascimento@example.com', 'senhaPaulo16', 'Paulo Nascimento', '1983-05-17'),
('renata.fonseca@example.com', 'senhaRenata17', 'Renata Fonseca', '1989-07-22'),
('rafael.castro@example.com', 'senhaRafael18', 'Rafael Castro', '1986-11-11'),
('sara.lima@example.com', 'senhaSara19', 'Sara Lima', '1998-01-29'),
('tiago.dias@example.com', 'senhaTiago20', 'Tiago Dias', '1985-12-03'),
('uriel.barros@example.com', 'senhaUriel21', 'Uriel Barros', '1990-06-06'),
('valeria.moreira@example.com', 'senhaValeria22', 'Valeria Moreira', '1982-10-19'),
('wagner.farias@example.com', 'senhaWagner23', 'Wagner Farias', '1979-03-11'),
('xavier.duarte@example.com', 'senhaXavier24', 'Xavier Duarte', '1993-08-27'),
('yara.bezerra@example.com', 'senhaYara25', 'Yara Bezerra', '1995-12-31'),
('zeca.azevedo@example.com', 'senhaZeca26', 'Zeca Azevedo', '1988-04-04'),
('andre.silva@example.com', 'senhaAndre27', 'André Silva', '1987-07-07'),
('bianca.souza@example.com', 'senhaBianca28', 'Bianca Souza', '1994-02-02'),
('carlos.pereira@example.com', 'senhaCarlos29', 'Carlos Pereira', '1981-11-25'),
('daniela.costa@example.com', 'senhaDaniela30', 'Daniela Costa', '1992-06-16'),
('everton.gomes@example.com', 'senhaEverton31', 'Everton Gomes', '1986-03-03'),
('flavia.martins@example.com', 'senhaFlavia32', 'Flávia Martins', '1990-07-30'),
('gustavo.ribeiro@example.com', 'senhaGustavo33', 'Gustavo Ribeiro', '1984-05-15'),
('helena.rocha@example.com', 'senhaHelena34', 'Helena Rocha', '1993-09-12'),
('igor.almeida@example.com', 'senhaIgor35', 'Igor Almeida', '1989-01-05'),
('juliana.mendes@example.com', 'senhaJuliana36', 'Juliana Mendes', '1991-08-08'),
('kaua.oliveira@example.com', 'senhaKaua37', 'Kauã Oliveira', '1997-11-20'),
('lara.castro@example.com', 'senhaLara38', 'Lara Castro', '1995-05-03'),
('miguel.fernandes@example.com', 'senhaMiguel39', 'Miguel Fernandes', '1982-12-12'),
('nicole.santos@example.com', 'senhaNicole40', 'Nicole Santos', '1990-03-28'),
('otavio.dias@example.com', 'senhaOtavio41', 'Otávio Dias', '1987-09-19'),
('priscila.nascimento@example.com', 'senhaPriscila42', 'Priscila Nascimento', '1985-02-10'),
('ricardo.lopes@example.com', 'senhaRicardo43', 'Ricardo Lopes', '1983-06-08'),
('sabrina.lima@example.com', 'senhaSabrina44', 'Sabrina Lima', '1992-10-25'),
('thiago.correia@example.com', 'senhaThiago45', 'Thiago Correia', '1991-04-04'),
('vinicius.soares@example.com', 'senhaVinicius46', 'Vinicius Soares', '1988-08-16'),
('wallace.araujo@example.com', 'senhaWallace47', 'Wallace Araújo', '1978-11-07'),
('ygor.teixeira@example.com', 'senhaYgor48', 'Ygor Teixeira', '1994-12-15'),
('zuleica.ramos@example.com', 'senhaZuleica49', 'Zuleica Ramos', '1990-05-11'),
('leticia.carvalho@example.com', 'senhaLeticia50', 'Leticia Carvalho', '1993-07-21');

insert into Genero_Usuario (email, genero) VALUES
('ana.silva@example.com', 'mulher'),
('bruno.costa@example.com', 'homem'),
('carla.oliveira@example.com', 'mulher'),
('daniel.pereira@example.com', 'homem'),
('eduarda.gomes@example.com', 'mulher'),
('felipe.santos@example.com', 'homem'),
('gabriela.rocha@example.com', 'mulher'),
('henrique.souza@example.com', 'homem'),
('isabela.mendes@example.com', 'mulher'),
('joao.martins@example.com', 'homem'),
('karina.almeida@example.com', 'mulher'),
('leonardo.ribeiro@example.com', 'homem'),
('mariana.carvalho@example.com', 'mulher'),
('natan.dias@example.com', 'homem'),
('olivia.azevedo@example.com', 'mulher'),
('paulo.nascimento@example.com', 'homem'),
('renata.fonseca@example.com', 'mulher'),
('rafael.castro@example.com', 'homem'),
('sara.lima@example.com', 'mulher'),
('tiago.dias@example.com', 'homem'),
('uriel.barros@example.com', 'homem'),
('valeria.moreira@example.com', 'mulher'),
('wagner.farias@example.com', 'homem'),
('xavier.duarte@example.com', 'homem'),
('yara.bezerra@example.com', 'mulher'),
('zeca.azevedo@example.com', 'homem'),
('andre.silva@example.com', 'homem'),
('bianca.souza@example.com', 'mulher'),
('carlos.pereira@example.com', 'homem'),
('daniela.costa@example.com', 'mulher'),
('everton.gomes@example.com', 'homem'),
('flavia.martins@example.com', 'mulher'),
('gustavo.ribeiro@example.com', 'homem'),
('helena.rocha@example.com', 'mulher'),
('igor.almeida@example.com', 'homem'),
('juliana.mendes@example.com', 'mulher'),
('kaua.oliveira@example.com', 'homem'),
('lara.castro@example.com', 'mulher'),
('miguel.fernandes@example.com', 'homem'),
('nicole.santos@example.com', 'mulher'),
('otavio.dias@example.com', 'homem'),
('priscila.nascimento@example.com', 'mulher'),
('ricardo.lopes@example.com', 'homem'),
('sabrina.lima@example.com', 'mulher'),
('thiago.correia@example.com', 'homem'),
('vinicius.soares@example.com', 'homem'),
('wallace.araujo@example.com', 'homem'),
('ygor.teixeira@example.com', 'homem'),
('zuleica.ramos@example.com', 'mulher'),
('leticia.carvalho@example.com', 'mulher');

